version: '3'
services:
  # Service for the Postgres Database for Airflow
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Service to initialize the Airflow database
  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Your --lastname Name --role Admin --email admin@example.com
      "

  # Service for the Airflow Webserver
  airflow-webserver:
    build:
      context: ./airflow
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data  # <-- Makes data/ available inside the container
      - ./scripts:/opt/airflow/scripts # <-- Makes scripts/ available inside the container
      - ./airflow/logs:/opt/airflow/logs
      - ./mlruns:/opt/airflow/mlruns # <-- Mount mlruns folder
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver
  
  # Service for the Airflow Scheduler
  airflow-scheduler:
    build:
      context: ./airflow
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./airflow/logs:/opt/airflow/logs
      - ./mlruns:/opt/airflow/mlruns
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: scheduler

  # Service for MLflow Tracking Server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    container_name: mlflow-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns # <-- Persist MLflow data on host
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri file:///mlruns
      --default-artifact-root file:///mlruns

volumes:
  postgres-db-volume: